src/Entity/Product.php
<?php

namespace App\Entity;

use App\Repository\ProductRepository;
use DateTime;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\HttpFoundation\File\File;



#[ORM\Entity(repositoryClass: ProductRepository::class)]
#[Vich\Uploadable]
class Product
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom = null;

    #[ORM\Column]
    private ?float $Prix = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $createdAt = null;
    public function __construct()
    {
        $this->createdAt = new DateTime('now');
    }
    #[ORM\ManyToOne(inversedBy: 'products')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Category $category = null;

    #[ORM\Column(length: 255)]
    private ?string $slug = null;

    #[ORM\Column(length: 255, type: 'string')]
    private ?string $image = null;

    #[Vich\UploadableField(mapping: 'products', fileNameProperty: 'image')]
    private ?File $imageFile = null;

    #[ORM\Column]
    private ?bool $online = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $sousTitre = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $updatedAt = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrix(): ?float
    {
        return $this->Prix;
    }

    public function setPrix(float $Prix): self
    {
        $this->Prix = $Prix;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }


    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;

        if (null !== $imageFile) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->updatedAt = new \DateTimeImmutable();
        }
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function isOnline(): ?bool
    {
        return $this->online;
    }

    public function setOnline(bool $online): self
    {
        $this->online = $online;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSousTitre(): ?string
    {
        return $this->sousTitre;
    }

    public function setSousTitre(string $sousTitre): self
    {
        $this->sousTitre = $sousTitre;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(?\DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }
}

src/Controller/CartController.php
<?php

namespace App\Controller;

use App\Service\CartService;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class CartController extends AbstractController
{

    #[Route('/mon-panier', name: 'panier_card')]
    public function index(CartService $cartService): Response
    {
        return $this->render('cart/index.html.twig', [
            'cart' => $cartService->getTotal()
        ]);
    }

    #[Route('/mon-panier/{id<\d+>}', name: 'addTo_panier')]
    public function addItem(CartService $cartService, int $id): RedirectResponse
    {
        $cartService->addToCart($id);
        $this->addFlash('success', 'Produit a bien été ajoutée');
        return $this->redirectToRoute("product_home");
    }

    #[Route('/mon-panier/remove/{id<\d+>}', name: 'remove_item')]
    public function removeItem(CartService $cartService, int $id): RedirectResponse
    {
        $cartService->removeFromCart($id);
        return $this->redirectToRoute("panier_card");
    }


    #[Route('/mon-panier/increase/{id<\d+>}', name: 'cart_increase')]
    public function quantiteIncrease(CartService $cartService, int $id): RedirectResponse
    {
        $cartService->addToCart($id);
        return $this->redirectToRoute("panier_card");
    }


    #[Route('/mon-panier/decrease/{id<\d+>}', name: 'cart_decrease')]
    public function quantityDecrease(CartService $cartService, int $id): RedirectResponse
    {
        $cartService->decreaseQuantityFromCart($id);
        return $this->redirectToRoute("panier_card");
    }


    #[Route('/mon-panier/vide', name: 'panier_vide')]
    public function addToRouteSupprimer(CartService $cartService): RedirectResponse
    {
        $cartService->removeCart();
        return $this->redirectToRoute("panier_card");
    }
}

templates/cart/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mon Panier!
{% endblock %}

{% block body %}

    {# {{dump(cart)}} #}
    {% if cart|length>0 %}
        <section class="h-100 mt-5">
        <div class="container bg-light h-100 shadow-lg">
            <div class="row  p-5  d-flex justify-content-center align-items-center h-100">
                <div class="col-10">

                    <div class=" mt-4 mb-4">
                        <h3 class="fw-bold mb-0 text-info text-end">Mon Panier</h3>
                    </div>


                    <p class="h6 mb-0 mt-3 text-end">Souhaitez-vous ajouter d'autre produits? &nbsp
                        <a href="{{ path('product_home') }}" class="btn btn-sm btn-outline-info">
                            Voir les listes
                        </a>
                    </p>

                    {# {% set itemtotalPrix = null %} #}

                    {% set grandTotal = null %}
                    {% set quantityTotal = null %}
                    {% for item in cart %}
                        {% set itemtotalPrix = item.product.prix * item.quantity %}
                        {% set grandTotal = grandTotal + itemtotalPrix %}
                        {% set quantityTotal = quantityTotal + item.quantity %}

                        <div class=" rounded-3">
                            <div class="card-body p-4">
                                <div class="row d-flex justify-content-between align-items-center">
                                    <div class="col-md-2 col-lg-2 col-xl-2">
                                        <img src="{{ asset('uploads/images/products/'~ item.product.image ~'') }}"
                                             class="img-fluid rounded-3" alt="Cotton T-shirt">
                                    </div>
                                    <div class="col-md-3 col-lg-3 col-xl-3">
                                        <p class="lead fw-normal mb-2">{{ item.product.nom }}</p>


                                        <span class="text-muted">Prix Unitaire:
											{{ item.product.prix }}
										</span>

                                    </div>

                                    <div class="col-md-3 col-lg-3 col-xl-2 d-flex">
                                        <a href="{{ path('cart_decrease', {'id': item.product.id}) }}"
                                           class="btn btn-link px-2">
                                            <i class="bi bi-dash-square-fill text-secondary"
                                               style="font-size: 1.2rem;"></i>
                                        </a>

                                        <label>
                                            <input value="{{ item.quantity }}" type="number" class="form-control"/>
                                        </label>

                                        <a href="{{ path('cart_increase', {'id': item.product.id}) }}"
                                           class="btn btn-link px-2">
                                            <i class="bi bi-plus-square-fill text-secondary"
                                               style="font-size: 1.2rem;"></i>
                                        </a>
                                    </div>
                                    <div class="col-md-3 col-lg-2 col-xl-2 offset-lg-1 ">
                                        <h5 class="mb-0">
                                            {{ (itemtotalPrix)|number_format(2, ',', ',') }}
                                            €
                                        </h5>
                                    </div>
                                    <div class="col-md-1 col-lg-1 col-xl-1 text-end">
                                        <a href="{{ path('remove_item', {id:item.product.id}) }}"
                                           onclick="return confirm('Êtes-vous sûr de supprimer ce produit ?')"
                                           class="text-secondary">
                                            <i class="bi bi-trash3" style="font-size: 1.5rem; color: gray;"></i>
                                        </a>
                                    </div>
                                    <hr class="mt-3">
                                </div>
                            </div>
                        </div>

                    {% endfor %}

                    <div class=" mb-3">
                        <div class="d-flex justify-content-between mx-3 mb-3">
                            <p class="text-secondary">
                                Produits Totale: &nbsp
                                <span class="fw-bold">{{ cart|length }}
							</span>
                            </p>
                            <p class="text-secondary">
                                Quantité totale: &nbsp
                                <span class="fw-bold">{{ quantityTotal }}
							</span>
                            </p>
                            <p class="bg-warning px-3 py-1">
                                PRIX TOTALE :
                                <span class="fw-bold h4">
								{{ grandTotal|number_format(2, ',', ',') }}€</span>
                            </p>
                        </div>

                        <div class=" mt-4 mb-4 d-flex justify-content-between ms-3">
                            <p class="h6 mb-0 mt-3 text-end">
                                <a href="{{ path('panier_vide') }}"
                                   onclick="return confirm('Êtes-vous sûr de supprimer votre panier ?')"
                                   class="text-danger">
                                    <i class="bi bi-trash3" style="font-size: .8rem;"></i>
                                    &nbsp Supprimer le panier?
                                </a>
                            </p>


                            <div class="text-end col-6">

                                {# !!!this is just for testing , it is not right to trust client side value!!! #}
                                <form action="/create-checkout-session?total_price={{ grandTotal }}" method="POST">
                                    <button type="submit" class="btn btn-info w-100">Valider mon panier</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        </section>{% else %}

        <div class="text-center mt-5">
            <div>
                <i class="bi bi-binoculars-fill " style="font-size: 1.3rem;"></i>
            </div>
            <br><br><br>
            <div>
                <i class="bi bi-cart-dash text-info" style="font-size: 4rem; "></i>
            </div>

            <h2 class="text-center text-danger mt-4">
                VOTRE PANIER EST VIDE</h2>

            <P>
                Commence votre shopping dès maintenant à travers nos articles
            </P>
            <div class="card-body text-center mb-3">
                <a href="{{ path('product_home') }}" type="button" class="btn btn-info">VOIR LES PRODUITS</a>
            </div>
        </div>


    {% endif %}{% endblock %}